name: Run Tests

on:
  pull_request:
  push:
    branches:
      - main
  create:
    tags:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.3

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

  unit_tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.3

      - name: Restore bundle cache and install dependencies
        run: bundle install --jobs 4 --retry 3
      - name: Run unit tests
        run: bundle exec rails test:units

  integration_tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      - name: Restore bundle cache and install dependencies
        run: bundle install --jobs 4 --retry 3
      - name: Run integration tests
        run: bundle exec rails test:integration
